spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: 'jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL'